"""add companies lia_placements attendance_records and course_type

Revision ID: 14a8e61bf58f
Revises: 7a83bd49c59d
Create Date: 2026-03-03 13:53:25.522124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a8e61bf58f'
down_revision: Union[str, None] = '7a83bd49c59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_type', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_courses_course_type'), 'courses', ['course_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_course_type'), table_name='courses')
    op.drop_column('courses', 'course_type')
    # ### end Alembic commands ###
